### ISSUE TITLE
Update make_proto.sh and README.md

### ISSUE THREAD

**Issue by tomjad** [techmo-pl/dictation-client#26]
Fix make_proto.sh script. Run `sed` only when this line to replace is really incorrect:
https://github.com/techmo-pl/dictation-client/blob/2cfa6826a5eea6cf158c69567109966c839669fb/python/make_proto.sh#L26

Reason: customer reports problems with incorrect syntax, probably because of make_proto.sh was run many times:
```
File "dictation_asr_pb2_grpc.py", line 4
    from . from . from . import dictation_asr_pb2 as dictation__asr__pb2
              ^
SyntaxError: invalid syntax
```
------------

Update **Readme** - mark section with proto-files regeneration as an optional. This is now first step and someone runs this step

**Comment by paweljaciow** [comment]
Something else must go wrong by that customer. [This instruction](https://github.com/techmo-pl/dictation-client/blob/2cfa6826a5eea6cf158c69567109966c839669fb/python/make_proto.sh#L18) creates a new file (with buggy import) and this `sed` fixes that. What you reported indicates that the file is not being created and `sed` multiplies the substitution in an already existing file. I will fix that multiplication (`sed` will replace the whole line, not only the match) but the customer is not generating the sources properly.

**Comment by paweljaciow** [comment]
Closed in: https://github.com/techmo-pl/dictation-client/pull/27 .
